all: exercise1 exercise2 exercise3 exercise4 exercise5 exercise6 time

exercise1: 1-systemcalls.c
	gcc 1-systemcalls.c -o exercise1

exercise2: 2-processes.c
	gcc 2-processes.c -o exercise2

exercise3: 3-exec.c
	gcc 3-exec.c -o exercise3

exercise4: 4-wait.c
	gcc 4-wait.c -o exercise4

exercise5: 5-waitpid.c
	gcc 5-waitpid.c -o exercise5

exercise6: 6-pipe.c
	gcc 6-pipe.c -o exercise6

time: time.c
	gcc time.c -o time